config/routes.rb
# encoding: utf-8
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'leads#index'

  get "/signup" => 'leads#new'

  post "/upload" => 'leads#upload'

  get "leads/:id" => 'leads#show'

  resources :leads, only: [:new, :create, :show, :index]

end

app/models/lead.rb
# encoding: utf-8
# frozen_string_literal: true

class Lead < ActiveRecord::Base
	key = SecureRandom.random_bytes(32)
	iv = SecureRandom.random_bytes(12)

	attr_encrypted_options.merge!(:encode => true)
	attr_encrypted :title, key: key, iv: iv
	attr_encrypted :first_name, key: key, iv: iv
	attr_encrypted :last_name, key: key, iv: iv
	attr_encrypted :email, key: key, iv: iv
	attr_encrypted :phone_number, key: key, iv: iv

end

app/controllers/application_controller.rb
# encoding: utf-8
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/leads_controller.rb
# encoding: utf-8
# frozen_string_literal: true

class LeadsController < ApplicationController
    # attr_encrypted :ssn, key: 'This is a key that is 256 bits!!'

  def index
    @leads = Lead.all
  end


  def new
    @lead = Lead.new
  end

  def create
    # raise lead_params
    @lead = Lead.create(lead_params)
    render :new unless @lead.persisted?
  end

  def show
    @lead = Lead.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        pdf = LeadPdf.new(@lead)
        send_data pdf.render, 
        filename: "lead_#{@lead.encrypted_first_name}.pdf",
        type: "application/pdf",
        disposition: "inline"
      end
    end
  end

  def upload
    # Make an object in your bucket for your upload
    obj = S3_BUCKET.objects[params[:file].original_filename]

    # Upload the file
    obj.write(file: params[:file], acl: :public_read)

    # Create an object for the upload
    @upload = Upload.new(url: obj.public_url, name: obj.key)

    # Save the upload
    if @upload.save
      redirect_to uploads_path, success: 'File successfully uploaded'
    else
      flash.now[:notice] = 'There was an error'
      render :new
    end
  end

  def lead_params
    params.require(:lead).permit(:title, :first_name, :last_name, :email, :phone_number, :interest_rate, :down_payment, :loan_amount)
  end
end

app/helpers/application_helper.rb
# encoding: utf-8
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Goostify</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render partial: "shared/navbar" %>

<%= yield %>

</body>
</html>

app/views/leads/create.html.haml
%h4 Thank you! A loan officer will get in contact with you shortly! 

%p
	%strong ID
	= @lead.id
%p
	%strong First Name:
	= @lead.last_name 
%p
	%strong Last Name:
	= @lead.first_name 
%p
	%strong Email:
	= @lead.email 
%p
	%strong Phone Number:
	= @lead.phone_number 
%p
	%strong Interest Rate:
	= @lead.interest_rate 
%p
	%strong Loan Amount:
	= @lead.loan_amount 
%p
	%strong Down Payment:
	= @lead.down_payment 
%p 
	= link_to "Printable Receipt (PDF)", lead_path(@lead.id, format: "pdf") 
	= @lead.first_name

= form_tag upload_path, enctype: 'multipart/form-data' do
	= file_field_tag :file
	= submit_tag 'Upload file'

%small Built with Ruby on Rails, PostgreSQL, HAML, and SASS, 

app/views/leads/index.html.haml
<h1>Goostify</h1>
<p>Roostify's handsome cousin (Under Construction)</p>
<a href="/signup">Give us a try!</a>

.carousel.slide{:id=>"slide-images", :data => {:ride => "carousel"}}
	%ol
		%li.active{:data => {:target => "slide-images", :slide_to => "0"}}
		%li{:data => {:target => "slide-images", :slide_to => "1"}}
		%li{:data => {:target => "slide-images", :slid1_to => "2"}}
	.carousel-inner
		.item.active
			%img{:src => "@path slider1.jpg", :alt => ""}/
		.item
			%img{:src => "@path slider2.jpg", :alt => ""}/
		.item
			%img{:src => "@path slider3.jpg", :alt => ""}/

	%a.left.carousel-control{:href => "#slide-images", :data => {:slide => "prev"}}
		%span.glyphicon.glyphicon-chevron-left
	%a.right.carousel-control{:href => "#slide-images", :data => {:slide => "next"}}
		%span.glyphicon.glyphicon-chevron-right

app/views/leads/new.html.erb
<%= form_for @lead do |lead_form| %>

  <div class="personal-details">
    <%=lead_form.label(:title, "Title")%>
    <%=lead_form.select(:title, options_for_select([["Title", "0"], ["Mr.", "Mr."], ["Mrs.", "Mrs."], ["Ms.", "Ms."], ["Dr.", "Dr."], ["Prof.", "Prof."]], selected: "0", disabled: ["0"]), :name => "title") %>

    <%=lead_form.label :first_name, "First Name" %>
    <%=lead_form.text_field :first_name %>

    <%=lead_form.label :last_name, "Last Name" %>
    <%=lead_form.text_field :last_name %>

    <%=lead_form.label(:phone_number, "Phone Number")%>
    <%=lead_form.text_field(:phone_number)%>

    <%=lead_form.label(:email, "Email")%>
    <%=lead_form.text_field(:email)%>
  </div>
  <div class="loan-details">
    <%=lead_form.label(:interest_rate)%>
    <%=lead_form.text_field(:interest_rate)%>

    <%=lead_form.label(:loan_amount)%>
    <%=lead_form.text_field(:loan_amount)%>

    <%=lead_form.label(:down_payment)%>
    <%=lead_form.text_field(:down_payment)%>
  </div>

  <%= lead_form.submit('Start Loan Application') %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Goostify</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/signup">Sign up</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>